{{- range .Values.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-%s-%s" $.Values.subject.name . $.Values.accessMode | trunc 63 | lower }}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ if eq $.Values.accessMode "ro" }}namespace-views{{ else }}namespace-edits{{ end }}
subjects:
- kind: {{ $.Values.subject.kind }}
  name: {{ $.Values.subject.name }}
---
{{- end }}

